function GLW_TestAll
% GLW_Wedge - Test all the non-HDR, non-Bits++, non-Stereo GLWindow examples
    
    programs = {...
        'GLW_Wedge' ...
        'GLW_Text' ...
        'GLW_MultipleObjects' ...
        'GLW_MulticoloredText' ...
        'GLW_Mondrian' ...
        'GLW_Image' ...
        'GLW_Gabor' ...
        'GLW_CircularApertureStimulus' ...
        'GLW_Basic' ...
        'GLW_Basic2' ...
        };
    
    for k = 1:numel(programs)
        fprintf('\nHit enter to continue with script ''%s''.\n', programs{k});
        pause;
        eval(programs{k}); 
    end

end

